# Generated by Django 5.1.7 on 2025-03-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='electco',
        ),
        migrations.RemoveField(
            model_name='district',
            name='electco',
        ),
        migrations.RemoveField(
            model_name='region',
            name='electco',
        ),
    ]
