# Generated by Django 5.1.7 on 2025-03-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govote', '0003_candidate_profile_alter_area_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
