# Generated by Django 5.1.7 on 2025-03-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govote', '0004_alter_title_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Voter List'},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.RemoveField(
            model_name='election',
            name='electco',
        ),
        migrations.RemoveField(
            model_name='election',
            name='voteYN',
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='govote.position'),
        ),
        migrations.AddField(
            model_name='position',
            name='vote_type',
            field=models.CharField(choices=[('single', 'Single Candidate Selection'), ('multiple', 'Multiple Candidate Selection'), ('yes_no', 'Yes/No Vote')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='vote',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='govote.position'),
        ),
        migrations.AlterField(
            model_name='election',
            name='max_vote',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending Approval')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='position',
            name='max_vote',
            field=models.IntegerField(default=1),
        ),
    ]
