# Generated by Django 5.1.7 on 2025-03-11 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govote', '0005_alter_vote_options_alter_voter_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
