# Generated by Django 5.1.7 on 2025-03-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govote', '0006_alter_election_end_date_alter_election_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='voteYN',
        ),
    ]
