# Generated by Django 5.1.7 on 2025-03-12 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govote', '0008_alter_position_created_by_alter_position_modified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Election Candidates'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Election Positions'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Election Votes'},
        ),
        migrations.CreateModel(
            name='YesNoOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_label', models.CharField(default='Yes', max_length=50)),
                ('no_label', models.CharField(default='No', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='position/YesNoOption/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_ynoption', to=settings.AUTH_USER_MODEL)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yes_no_option', to='govote.position')),
            ],
            options={
                'verbose_name_plural': 'Election Positions YN',
                'ordering': ['-created_at'],
            },
        ),
    ]
