# Generated by Django 5.1.7 on 2025-03-12 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govote', '0010_remove_yesnooption_no_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yesnooption',
            options={},
        ),
        migrations.AlterField(
            model_name='yesnooption',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yes_no_options', to='govote.position'),
        ),
        migrations.AlterField(
            model_name='yesnooption',
            name='vote_yn',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AddConstraint(
            model_name='yesnooption',
            constraint=models.UniqueConstraint(fields=('position', 'vote_yn'), name='unique_yes_no_option'),
        ),
    ]
