# Generated by Django 5.1.7 on 2025-03-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govote', '0011_alter_yesnooption_options_alter_yesnooption_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yesnooption',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Election Position YesNoOption'},
        ),
    ]
